spring:
  datasource:
    url: jdbc:postgresql://dpg-cjdcq5gq339s73f0lbcg-a.oregon-postgres.render.com:5432/database_postgre_example_one
    username: database_postgre_example_one_user
    password: 22nzcGPgiAnT6e9bP8sgUm1bGWKp9wsc
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        # use_nationalized_character_data: true
        enable_lazy_load_no_trans: true
        format_sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: hoangduynam20996@gmail.com
    password: fuaycypcqvrdsjyy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  tomcat:
    accesslog:
      enabled: true