spring:
  datasource:
    url: jdbc:postgresql://${ASSIGN_JAVA_FIVE_NETWORK:localhost}:5432/${DB_ASSIGN_JAVA_FIVE:assign_java_five}
    username: postgres
    password: ${ASSIGN_JAVA_FIVE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        # use_nationalized_character_data: true
        #        enable_lazy_load_no_trans: true
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: staying.booking.online@gmail.com
    password: cfoarjgkprvmvgvx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
# Bug sercurity
logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  max-http-header-size: 20000
  tomcat:
    accesslog:
      enabled: true
  port: 8080

#Permission
admin:
  admin-read: admin:read
  admin-create: admin:create
  admin-update: admin:update
  admin-delete: admin:delete

user:
  user-read: user:read
manager:
  manager-read: manager:read