spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/assign_java_five
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        # use_nationalized_character_data: true
        #        enable_lazy_load_no_trans: true
        format_sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: staying.booking.online@gmail.com
    password: cfoarjgkprvmvgvx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  max-http-header-size: 20000
  tomcat:
    accesslog:
      enabled: true
  port: 8080

myapp:
  http-link: http://localhost:8080/api/v1/auth/confirm?token=

#Permission
admin:
  admin-read: admin:read
  admin-create: admin:create
  admin-update: admin:update
  admin-delete: admin:delete

user:
  user-read: user:read
manager:
  manager-read: manager:read